services:
  streamlit:
    container_name: insel-streamlit
    # Build the image from the Dockerfile in the current directory
    build: .

    restart: unless-stopped

    develop:
      # Create a `watch` configuration to update the app
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment — it could be for a
          # different platform in the container
          ignore:
            - .venv/

        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./uv.lock


################################################################################
#                              Access the web app                              #
################################################################################

# NOTE: In order to access the web-app, please create a compose.override.yaml file.

########################
#    Shared network    #
########################

# For a reverse proxy, in an external network, which can access the app at http://insel-streamlit:8501:

# services:
#   streamlit:
#     networks:
#       - proxy-network
#
# networks:
#   proxy-network:
#     name: reverse_proxy
#     external: true

########################
#     Port binding     #
########################

# The app will be available at http://localhost:8501
#
# services:
#   streamlit:
#     ports:
#       - 127.0.0.1:8501:8501
